POST http://localhost:8080/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im9sYWp1ZG9pZ2dkc3NzZGdyQGdtYWlsLmNvbSIsIklkIjoxLCJSb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY4MzgxODF9.Wo-M47xrY33CT2m4AFC-gJP5ZH_mpmsteaTwKMGGYw4

{
    "Name": "update Wiredledss Mossssuse",
    "Description": "A smooth wireless mouse with ergonomic design",
    "Price": 25.99,
    "Quantity": 50
    
}
