DELETE http://localhost:8080/product/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im9sYWp1ZG9pZ2dkZGRkZGdyQGdtYWlsLmNvbSIsIklkIjoxLCJSb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY3Nzk0MzB9.QULBiiOcEJMR-K2EJg1kDx6cIutfvf3dWJu0CuiKB64