DELETE http://localhost:8080/product/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im9sYWp1ZG9pZ2dkc3NzZGdyQGdtYWlsLmNvbSIsIklkIjoyLCJSb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY3ODMwNjV9.gffWnCmwQkx1GkoznJhUi6R0Z_wxp5Tvh_7r7OEWzYs