DELETE http://localhost:8080/product/2
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im9sYWp1ZGdnZHNzc2RnckBnbWFpbC5jb20iLCJJZCI6MiwiUm9sZSI6ImFkbWluIiwiZXhwIjoxNzU3MDMxODQzfQ.qkHNP_lmlMmZNlkUWHnxh4Vo0gygJPTZKsWzrsH9evM