Get http://localhost:8080/order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im9sYWp1ZGdnZHNzc2RnckBnbWFpbC5jb20iLCJJZCI6MiwiUm9sZSI6ImFkbWluIiwiZXhwIjoxNzU3MDMyMjY4fQ.saopoVjcxd_sCeUNxuXekw3TpQ7kg7xIRFy-pcxWsYc